-- Art direction. Human faces are derived from the user's two supplied bases.
return {
 {key='swordsman',name='검사',kind='human',ref='rose',hair={'453c4b','655360','89707c','ae8990','d3a5aa','efd0c6','fff0db'},cloth={'36496e','587fc0','9ebde4'},weapon='sword',hat='clip'},
 {key='tank',name='탱커',kind='human',ref='teal',hair={'333747','4c4e61','747385','a09baa','c1bcc5','e1dbe0','faf1e8'},cloth={'454c69','757dae','bdc8e6'},weapon='shield',hat='helmet'},
 {key='berserker',name='버서커',kind='human',ref='rose',hair={'423139','65413c','945843','bb7851','dfa376','f4cea0','fff0d3'},cloth={'672f45','b34e61','efa187'},weapon='axe',hat='band'},
 {key='assassin',name='암살자',kind='human',ref='teal',hair={'302d43','4a435b','6c617e','94849e','bdb1c8','dfd3df','f4e8ea'},cloth={'342d56','63508e','ac96cd'},weapon='daggers',hat='hood'},
 {key='archer',name='궁수',kind='human',ref='rose',hair={'403847','61534f','8c7863','b79f7d','d9c49f','f0e2c1','fffae7'},cloth={'2b5b50','4a977a','a7d4a0'},weapon='bow',hat='leaf'},
 {key='sniper',name='저격수',kind='human',ref='teal',hair={'323944','4c5361','707d88','95a5ad','bdced1','e0ebdf','f6fae8'},cloth={'434757','707c99','b3c1ca'},weapon='rifle',hat='cap'},
 {key='mage',name='마법사',kind='human',ref='teal',hair={'3b334b','5c476b','87668e','ae8db6','ccb0d0','ead4e4','fff0f0'},cloth={'3b396e','7770b7','b5b0e0'},weapon='staff',hat='witch'},
 {key='summoner',name='소환사',kind='human',ref='rose',hair={'344744','526560','748f87','95b4a4','bed3bf','e4e8cf','fff8df'},cloth={'355958','599b96','b0dace'},weapon='book',hat='circlet'},
 {key='healer',name='힐러',kind='human',ref='teal',hair={'4d3d47','705964','957883','b99a9f','dfbebd','f2ddcc','fff6df'},cloth={'755577','b08bb6','e9c8da'},weapon='holy',hat='nun'},
 {key='monster_slime_swarm',name='슬라임 무리',kind='slime',theme='mint'},
 {key='monster_wild_dogs',name='들개 떼',kind='beast',theme='ochre'},
 {key='monster_goblin_scouts',name='고블린 정찰조',kind='goblin',theme='green'},
 {key='monster_cave_bats',name='동굴 박쥐 떼',kind='bat',theme='violet'},
 {key='monster_mushroom_grove',name='독버섯 군락',kind='mushroom',theme='rose'},
 {key='monster_giant_slime',name='거대 슬라임',kind='slime',theme='blue',boss=true},
 {key='monster_orc_warband',name='오크 전사대',kind='goblin',theme='green',orc=true},
 {key='monster_harpy_flock',name='하피 무리',kind='harpy',theme='rose'},
 {key='monster_living_armor',name='리빙 아머',kind='armor',theme='blue'},
 {key='monster_bandit_crew',name='도적단',kind='bandit',theme='ochre'},
 {key='monster_wraith_choir',name='망령 성가대',kind='ghost',theme='mint'},
 {key='monster_orc_chieftain',name='오크 대족장',kind='goblin',theme='green',orc=true,boss=true},
 {key='monster_ancient_golem',name='고대 골렘',kind='golem',theme='stone',boss=true},
 {key='monster_frost_dragon',name='서리 드래곤',kind='dragon',theme='blue',boss=true},
 {key='monster_inferno_lord',name='화염 거인',kind='golem',theme='fire',boss=true,fire=true},
 {key='monster_lich_host',name='리치의 군세',kind='skeleton',theme='violet',lich=true},
 {key='monster_abyss_pack',name='심연의 마수 무리',kind='beast',theme='shadow',horns=true},
 {key='monster_demon_legion',name='마신 군단',kind='demon',theme='rose'},
 {key='summon_beast',name='야수',kind='beast',theme='blue',summon=true},
 {key='summon_spirit',name='정령',kind='spirit',theme='mint'},
 {key='summon_skeleton',name='해골',kind='skeleton',theme='ochre'},
 {key='summon_turret',name='화살탑',kind='turret',theme='ochre'},
}
